### ISSUE TITLE
one error in richview.kt

### ISSUE THREAD

**Issue by hougys** [yanex/anko-template-project#16]
in richview.kt
    private fun init() = AnkoContext.createDelegate(this).apply {
    gravity = CENTER

I need add var gravity,why?

**Comment by thoaihuynhnguyen** [comment]
Error super, how to fix it?

 constructor(context: Context?, attrs: AttributeSet?, defStyleAttr: Int) : super(context, attrs, defStyleAttr) {
        init()
    }

**Comment by yanex** [comment]
The issue is closed as Anko is [deprecated](https://github.com/Kotlin/anko/blob/16ff09b952f8fb3ce2c6107caf6e788ef50ec19f/GOODBYE.md).
