### ISSUE TITLE
about a complex list viewholder

### ISSUE THREAD

**Issue by 29995270** [yanex/anko-template-project#2]
Thanks for your example.
If my viewholder has a lot of views, how can i handle their reference.
Should i set a id in anko expression, and findViewById in viewholder?

**Comment by yanex** [comment]
The issue is closed as Anko is [deprecated](https://github.com/Kotlin/anko/blob/16ff09b952f8fb3ce2c6107caf6e788ef50ec19f/GOODBYE.md).
