### ISSUE TITLE
Can you explain these two lines?

### ISSUE THREAD

**Issue by desertjim** [yanex/anko-template-project#3]
https://github.com/yanex/anko-example/blob/master/app/src/main/java/org/example/ankodemo/RichView.kt#L63-L64

I tried reading the anko docs but there is a lot going on there.
Thanks!

**Comment by NeverwinterMoon** [comment]
@desertjim This is explained here: https://github.com/Kotlin/anko/blob/master/doc/ADVANCED.md#user-content-extending-anko and here: https://github.com/Kotlin/anko#user-content-is-it-extensible

**Comment by yanex** [comment]
Updated link: https://github.com/Kotlin/anko/wiki/Anko-Layouts#is-it-extensible.
