### ISSUE TITLE
Can't build a sample project.

### ISSUE THREAD

**Issue by dmitvitalii** [yanex/anko-template-project#7]
Android Studio 2.2.3, java-8 OpenJDK, Fedora 24. Just downloaded and opened project.

Error:(41, 13) Failed to resolve: org.jetbrains.anko:anko-sdk15:0.9.1

**Comment by jakoss** [comment]
Same problem with me

**Comment by carmas123** [comment]
+1

**Comment by NeverwinterMoon** [comment]
Version 0.9.1 is not available at jcenter (only previous release is), I solved this by adding `maven { url 'https://dl.bintray.com/jetbrains/anko' }` to allprojects repositories in root build.gralde, like so:

```

allprojects {
    repositories {
        jcenter()
        maven { url 'https://dl.bintray.com/jetbrains/anko' }
    }
}
```

**Comment by justiceadamsUNI** [comment]
+1 @NeverwinterMoon Thank you for the help!

**Comment by yujiea** [comment]
@Nekromancer  Thank you for your help !

**Comment by MindaugasD1986** [comment]
Helped me alot thanks ;D

**Comment by yanex** [comment]
The actual problem https://github.com/Kotlin/anko/issues/313 is resolved so I think the issue may be closed.
